// <auto-generated />
using Day44ThreadDemo.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Day44ThreadDemo.Migrations
{
    [DbContext(typeof(FeedDataDbContext))]
    [Migration("20220520124327_InitialDb")]
    partial class InitialDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Day44ThreadDemo.DataAccess.Models.Feed", b =>
                {
                    b.Property<int>("MyTestKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MyTestKey"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Id")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Location")
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Title")
                        .HasColumnType("varchar(2000)");

                    b.HasKey("MyTestKey");

                    b.ToTable("Feeds");
                });
#pragma warning restore 612, 618
        }
    }
}
